import ROUTES from './route';
import DATE_TIME_PICKER_TYPES from './dateTimePickerType';
import {
  SERVICE,
  ERROR_CODE_SYSTEM,
  ERROR_CODE_PORTAL_SERVICE,
  ERROR_CODE_PAYMENT_SERVICE,
  ERROR_CODE_CALL_SERVICE,
  ERROR_CODE_PUBLIC_SERVICE,
} from './responseCode';
import {
  HOTLINE_TYPE,
  HOTLINE_STATUS,
  MOBILE_NETWORK_OPERATOR,
} from './hotline';

export const A_WEEK = 7 * 24 * 60 * 60 * 1000;
export const PAGINATION_LIMIT = 10;
export const ALL = 'ALL';

export {
  ROUTES,
  DATE_TIME_PICKER_TYPES,
  SERVICE,
  ERROR_CODE_SYSTEM,
  ERROR_CODE_PORTAL_SERVICE,
  ERROR_CODE_PAYMENT_SERVICE,
  ERROR_CODE_CALL_SERVICE,
  ERROR_CODE_PUBLIC_SERVICE,
  HOTLINE_TYPE,
  HOTLINE_STATUS,
  MOBILE_NETWORK_OPERATOR,
};
