name: Pull request

on:
  pull_request:
    types: [opened, reopened]

jobs:
  continuous-integration:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: |
          cp src/environments/.env.dev .env
          npm i --force
          npm run build
